### ISSUE TITLE
compatibilitytools.d path used by script is not picked up by Steam

### ISSUE THREAD

**Issue by JeremyKennedy** [patrickm32/proton-ge-custom-updater#3]
This must be specific to my distro (Ubuntu 20.04) or perhaps legacy folder structure, I'm not sure exactly. But by default the script places the files under `$HOME/.steam/steam/compatibilitytools.d`, which for me was not picked up by Steam. Instead, I had to use `$HOME/.steam/compatibilitytools.d`, which worked as expected.

Note that when testing this, I did not have conflicting `compatibilitytools.d` folders, so this isn't a case of Steam finding what I had already instead of what was produced by the script.

Here is the commit that fixed this script for me: https://github.com/JeremyKennedy/proton-ge-custom-updater/commit/d35339ffb69db2689fa6c28df86885c816a18e6d

Note that my Steam executable is under `$HOME/.steam/steam.sh`. I'm not sure what it is on your system, but maybe the `compatibilitytools.d` is supposed to be next to `steam.sh`? In which case you could look for that file.

Great script by the way! I was just thinking of writing something similar, I'm glad I came across your post.

**Comment by p-mng** [comment]
Hi, I'll try to fix the problem as soon as possible. A potential solution would be to check the directory for the `steam.sh` file before creating the `compatibilitytools.d` folder. I wouldn't remove `$HOME/.steam/steam` completely because this is a symbolic link to the .local folder on my installation so it might break the script for other people.

> But by default the script places the files under `$HOME/.steam/steam/compatibilitytools.d`

Actually the script should prefer `$HOME/.local/share/Steam`, but as far as I know this directory does not exist on Ubuntu. Is that correct?

**Comment by p-mng** [comment]
Hi, I have fixed the issue as far as I can tell. A quick test with the latest version would be nice!

**Comment by JeremyKennedy** [comment]
I can confirm it works now! :smiley:
